import {StatusBarStyle} from 'react-native';

const BAR_STYLE: StatusBarStyle = 'light-content';

export default {
  COLORS: {
    APP_BACKGROUND_COLOR: '#000000',
    STATUS_BAR_COLOR: '#000000',

    PRIMARY_COLOR: '#000000',
    SECONDARY_COLOR: '#BB85BB',
    TERTIARY_COLOR: '#FFFFFF',

    // Text colors
    PRIMARY_TEXT_COLOR: '#FFFFFF',
    SECONDARY_TEXT_COLOR: '#A2A2A2',

    // Button colors
    PRIMARY_BUTTON_COLOR: '#BB85BB',
    SECONDARY_BUTTON_COLOR: '#000000',
    TERTIARY_BUTTON_COLOR: '#FFFFFF',
    BUTTON_TEXT_COLOR: '#FFFFFF',

    //Text Input colors
    INPUT_BACKGROUND_COLOR: '#171717',
    INPUT_ACTIVE_BORDER_COLOR: '#BB85BB',
    INPUT_INACTIVE_BORDER_COLOR: '#2C2C2C',
    INPUT_TEXT_COLOR: '#FFFFFF',
    INPUT_PLACEHOLDER_COLOR: '#5d5d5d',

    //Chip colors
    PRIMARY_CHIP_COLOR: '#171717',
    CHIP_ACTIVE_BORDER_COLOR: '#BB85BB',
    CHIP_INACTIVE_BORDER_COLOR: '#2C2C2C',
    CHIP_TEXT_COLOR: '#FFFFFF',

    // RadioButton colors
    RADIO_BUTTON_BACKGROUND_COLOR: '#2B2B2B',
    RADIO_BUTTON_DOT_COLOR: '#FFFFFF',

    //Modal colors
    PRIMARY_MODAL_BACKGROUND_COLOR: 'rgba(0,0,0,0.8)',
    SECONDARY_MODAL_BACKGROUND_COLOR: '#FFFFFF',
    TERTIARY_MODAL_BACKGROUND_COLOR: '#171717',
    MODAL_TEXT_COLOR: '#000000',

    // Feed colors
    FEED_BACKGROUND_COLOR: '#171717',
    FEED_PRIMARY_TEXT_COLOR: '#FFFFFF',
    FEED_SECONDARY_TEXT_COLOR: '#8B8B8B',
    FEED_TERTIARY_TEXT_COLOR: '#BB85BB',

    // Switch colors
    SWITCH_ACTIVE_COLOR: '#00BC0E',
    SWITCH_INACTIVE_COLOR: '#262626',
    SWITCH_DOT_COLOR: '#FFFFFF',

    // Special colors
    RESET_PASSWORD_DESCRIPTION_COLOR: '#5C5C5C',
    SOCIAL_LOGIN_BORDER_COLOR: '#2C2C2C',
    SOCIAL_LOGIN_LABEL_COLOR: '#4D4D4D',
    SIGNUP_PROGRESS_BACKGROUND_COLOR: '#292C33',
    RESEND_CODE_COLOR: '#003FEB',
    PROFILE_TEXT_COLOR: '#5C5C5C',
    ALERT_BACKGROUND_COLOR: '#ff0000',
    CHAT_DOT_COLOR: '#ff0000',
    ALERT_TEXT_COLOR: '#969696',
    FILTER_TITLE_COLOR: '#464646',
    COMMENTS_TEXT_COLOR: '#464646',
    MODAL_BACKGROUND_COLOR: '#171717',
    COMPLETE_PROFILE_TEXT_COLOR: '#121111',
    PARTICIPANTS_TEXT_COLOR: '#626262',
    ACTIVE_RETINGS_COLOR: '#FFC107',
    INACTIVE_RETINGS_COLOR: '#3E3E3E',
    DIAMONDS_BACKGROUND_COLOR: '#AC72AC',
    DELETE_ACCOUNT_TEXT_COLOR: '#FF2626',
    COMPLETE_CHECK_ICON_COLOR: '#22B200'
  },
  FONTS: {
    MONTSERRAT: {
      BOLD: 'Montserrat-Bold',
      SEMI_BOLD: 'Montserrat-SemiBold',
      REGULAR: 'Montserrat-Regular',
      MEDIUM: 'Montserrat-Medium',
    },
  },
  BAR_STYLE: BAR_STYLE,
};
