export default [
  {
    id: 0,
    name: 'English',
    value: 'ENGLISH',
    isSelected: false,
  },
  {
    id: 1,
    name: 'Mandarin Chinese',
    value: 'MANDARIN_CHINESE',
    isSelected: false,
  },
  {
    id: 2,
    name: 'Spanish',
    value: 'SPANISH',
    isSelected: false,
  },
  {
    id: 3,
    name: 'Hindi',
    value: 'HINDI',
    isSelected: false,
  },
  {
    id: 4,
    name: 'Urdu',
    value: 'URDU',
    isSelected: false,
  },
  {
    id: 5,
    name: 'Arabic',
    value: 'ARABIC',
    isSelected: false,
  },
  {
    id: 6,
    name: 'Malay',
    value: 'MALAY',
    isSelected: false,
  },
  {
    id: 7,
    name: 'Russian',
    value: 'RUSSIAN',
    isSelected: false,
  },
  {
    id: 8,
    name: 'Bengali',
    value: 'BENGALI',
    isSelected: false,
  },
  {
    id: 9,
    name: 'Portuguese',
    value: 'PORTUGUESE',
    isSelected: false,
  },
  {
    id: 10,
    name: 'French',
    value: 'FRENCH',
    isSelected: false,
  },
  {
    id: 11,
    name: 'Hausa',
    value: 'HAUSA',
    isSelected: false,
  },
  {
    id: 12,
    name: 'Punjabi',
    value: 'PUNJABI',
    isSelected: false,
  },
  {
    id: 13,
    name: 'German',
    value: 'GERMAN',
    isSelected: false,
  },
  {
    id: 14,
    name: 'Japanese',
    value: 'JAPANESE',
    isSelected: false,
  },
  {
    id: 15,
    name: 'Persian',
    value: 'PERSIAN',
    isSelected: false,
  },
  {
    id: 16,
    name: 'Swahili',
    value: 'SWAHILI',
    isSelected: false,
  },
  {
    id: 17,
    name: 'Vietnamese',
    value: 'VIETNAMESE',
    isSelected: false,
  },
  {
    id: 18,
    name: 'Telugu',
    value: 'TELUGU',
    isSelected: false,
  },
  {
    id: 19,
    name: 'Italian',
    value: 'ITALIAN',
    isSelected: false,
  },
  {
    id: 20,
    name: 'Javanese',
    value: 'JAVANESE',
    isSelected: false,
  },
  {
    id: 21,
    name: 'Wu Chinese',
    value: 'WU_CHINESE',
    isSelected: false,
  },
  {
    id: 22,
    name: 'Korean',
    value: 'KOREAN',
    isSelected: false,
  },
  {
    id: 23,
    name: 'Tamil',
    value: 'TAMIL',
    isSelected: false,
  },
  {
    id: 24,
    name: 'Marathi',
    value: 'MARATHI',
    isSelected: false,
  },
  {
    id: 25,
    name: 'Yue Chinese',
    value: 'YUE_CHINESE',
    isSelected: false,
  },
  {
    id: 26,
    name: 'Dutch',
    value: 'DUTCH',
    isSelected: false,
  },
  {
    id: 27,
    name: 'Turkish',
    value: 'TURKISH',
    isSelected: false,
  },
  {
    id: 28,
    name: 'Indonesian',
    value: 'INDONESIAN',
    isSelected: false,
  },
];
