-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtUvIWZY2EQ0JUdIp
4oBeD7iVaaRCH/qHSyYoZLknwm+gCgYIKoZIzj0DAQehRANCAARUanNtKakUYZOn
d4eGWoGG8l91bf+a2QCMpStJto/HbmO8/I8y1TPAqEnqSTMr9S2PPHzTszJ0IyIi
RcjiDQkj
-----END PRIVATE KEY-----