name: Build Android

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 

      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0

      - name: Setup npm
        run: |
          npm i -g npm@8.6.0

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Build Android Release
        run: |
          cd android && ./gradlew clean && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
